import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer() {
  const footerLinks = [
    <Link href="/">home</Link>,
    <Link href="/cats">cats</Link>,
    <Link href="/favorites">favorites</Link>,
    <Link href="/schedule">schedule</Link>
  ];
  return (
    <div className="mt-8 bg-yellow-700 py-4 flex flex-col">
      <h1 className="text-center font-Lexend text-purple-950 font-black text-4xl">
        🐾 cat cafe 🐾
      </h1>
      <div>
        <ul className="flex justify-center space-x-2.5">
          {
            footerLinks.map((link, index) => (
              <React.Fragment key={index}>
                <li className="underline font-Lexend text-yellow-100 hover:text-yellow-200">{link}</li>
                {index !== footerLinks.length - 1 && <p>|</p>}
              </React.Fragment>
            )
            )
          }
        </ul>
      </div>
      <p className="font-Lexend text-yellow-400 text-center mt-4">
        (C) copyright brandon sibbitt 2025
      </p>
    </div>
  )
}

function Header() {
  return (
    <div className="flex justify-start bg-yellow-700 py-4 w-full mb-8 items-center">
      <Link href="/" className="font-Lexend font-black text-4xl text-purple-950 ml-8">cat cafe 🐾</Link>
      <nav>
        <div className="space-x-8 mx-8">
          <Link href="/cats" className="text-yellow-50 hover:text-yellow-200 font-Lexend">meet the cats</Link>
          <Link href="/favorites" className="text-yellow-50 hover:text-yellow-200 font-Lexend">my favorites</Link>
          <Link href="/schedule" className="text-yellow-50 hover:text-yellow-200 font-Lexend">schedule</Link>
        </div>
      </nav>
    </div>
  )
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
