import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer() {
  const footerLinks = [
    <Link href="/">home</Link>,
    <Link href="/cats">cats</Link>,
    <Link href="/favorites">favorites</Link>
  ];
  return (
    <div className="mt-8 bg-yellow-700 py-4 flex flex-col">
      <h1 className="text-center font-Lexend text-purple-950 font-black text-4xl">
        🐾 cat cafe 🐾
      </h1>
      <div>
        <ul className="flex justify-center space-x-2">
          {
            footerLinks.map((link) => <><li key={footerLinks.indexOf(link)} className="underline font-Lexend text-yellow-100 hover:text-yellow-200">{link}</li>{footerLinks.indexOf(link) !== footerLinks.length - 1 && <p>|</p>}</>)
          }
        </ul>
      </div>
    </div>
  )
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <nav className="bg-yellow-700 py-4 w-full mb-8 flex justify-start">
          <div className="space-x-8 mx-8">
            <Link href="/" className="text-yellow-50 hover:text-yellow-200 font-Lexend">home</Link>
            <Link href="/cats" className="text-yellow-50 hover:text-yellow-200 font-Lexend">meet the cats</Link>
            <Link href="/favorites" className="text-yellow-50 hover:text-yellow-200 font-Lexend">favorites</Link>
          </div>
        </nav>
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
